server:
  port: 5080

spring:
  application:
    name: buildly
  debug: true

  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: ${JWT_SECRET_KEY}

stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY}
  webhhook:
    secret-key: ${STRIPE_WEBHOOK_SECRET}

client:
  url: https://localhost:5080
